<fieldset class="filtri fieldset hide hide-for-print" id="filtri" data-toggler=".hide">
<legend>Cerca</legend>
<form id="formRicerca" class="formRicerca" method="get" action="/admin/view.aspx">
<input type="hidden" name="CoreModules_Ky" value="1" />
<input type="hidden" name="CoreEntities_Ky" value="24" />
<input type="hidden" name="CoreGrids_Ky" value="28" />
<div class="grid-x grid-padding-x number">
<div class="large-2 medium-2 small-4 cell">
<label for="AnagraficheContatti_Ky" class="large-text-right small-text-left middle">id</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="AnagraficheContatti_Ky" id="AnagraficheContatti_Ky" class="input-group-field" placeholder="ricerca per id">
</div>
</div>
<div class="grid-x grid-padding-x text">
<div class="large-2 medium-2 small-4 cell">
<label for="AnagraficheContatti_Email" class="large-text-right small-text-left middle">Email</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="AnagraficheContatti_Email" id="AnagraficheContatti_Email" class="input-group-field" placeholder="ricerca per Email">
</div>
</div>
<div class="grid-x grid-padding-x text">
<div class="large-2 medium-2 small-4 cell">
<label for="AnagraficheContatti_Nome" class="large-text-right small-text-left middle">Nome</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="AnagraficheContatti_Nome" id="AnagraficheContatti_Nome" class="input-group-field" placeholder="ricerca per Nome">
</div>
</div>
<div class="grid-x grid-padding-x text">
<div class="large-2 medium-2 small-4 cell">
<label for="AnagraficheContatti_Cognome" class="large-text-right small-text-left middle">Cognome</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="AnagraficheContatti_Cognome" id="AnagraficheContatti_Cognome" class="input-group-field" placeholder="ricerca per Cognome">
</div>
</div>
<div class="grid-x grid-padding-x">
<div class="large-12 medium-12 small-12 text-center">
<button type="submit" name="Submit" class="button success"><i class="fa-duotone fa-magnifying-glass fa-fw"></i>Cerca</button>
</div>
</div>
</form>
</fieldset>
