<fieldset class="filtri fieldset hide hide-for-print" id="filtri" data-toggler=".hide">
<legend>Cerca</legend>
<form id="formRicerca" class="formRicerca" method="get" action="/admin/view.aspx">
<input type="hidden" name="CoreModules_Ky" value="1" />
<input type="hidden" name="CoreEntities_Ky" value="23" />
<input type="hidden" name="CoreGrids_Ky" value="27" />
<div class="grid-x grid-padding-x number">
<div class="large-2 medium-2 small-4 cell">
<label for="AnagraficheCategorie_Ky" class="large-text-right small-text-left middle">id</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="AnagraficheCategorie_Ky" id="AnagraficheCategorie_Ky" class="input-group-field" placeholder="ricerca per id">
</div>
</div>
<div class="grid-x grid-padding-x text">
<div class="large-2 medium-2 small-4 cell">
<label for="AnagraficheCategorie_Titolo" class="large-text-right small-text-left middle">Titolo</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="AnagraficheCategorie_Titolo" id="AnagraficheCategorie_Titolo" class="input-group-field" placeholder="ricerca per Titolo">
</div>
</div>
<div class="grid-x grid-padding-x textarea">
<div class="large-2 medium-2 small-4 cell">
<label for="AnagraficheCategorie_Descrizione" class="large-text-right small-text-left middle">Descrizione</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="AnagraficheCategorie_Descrizione" id="AnagraficheCategorie_Descrizione" class="input-group-field" placeholder="ricerca per Descrizione">
</div>
</div>
<div class="grid-x grid-padding-x text">
<div class="large-2 medium-2 small-4 cell">
<label for="AnagraficheCategorie_Padre" class="large-text-right small-text-left middle">Padre</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="AnagraficheCategorie_Padre" id="AnagraficheCategorie_Padre" class="input-group-field" placeholder="ricerca per Padre">
</div>
</div>
<div class="grid-x grid-padding-x text">
<div class="large-2 medium-2 small-4 cell">
<label for="AnagraficheCategorie_Attributi" class="large-text-right small-text-left middle">Attributi</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="AnagraficheCategorie_Attributi" id="AnagraficheCategorie_Attributi" class="input-group-field" placeholder="ricerca per Attributi">
</div>
</div>
<div class="grid-x grid-padding-x">
<div class="large-12 medium-12 small-12 text-center">
<button type="submit" name="Submit" class="button success"><i class="fa-duotone fa-magnifying-glass fa-fw"></i>Cerca</button>
</div>
</div>
</form>
</fieldset>
