			<fieldset class="filtri fieldset hide hide-for-print" id="filtri" data-toggler=".hide">
					<legend>Cerca</legend>
					<form id="formRicerca1" class="formRicerca" method="get" action="/admin/view.aspx">
            <input type="hidden" name="CoreModules_Ky" value="26">
            <input type="hidden" name="CoreEntities_Ky" value="210">
            <input type="hidden" name="CoreGrids_Ky" value="218">
						<div class="grid-x grid-padding-x">
					    <div class="large-2 medium-2 small-3 cell">
					      <label for="Attributi_Titolo" class="large-text-right small-text-left middle">Titolo</label>
					    </div>
					    <div class="large-8 medium-8 small-6 cell">
			          <input type="text" name="Attributi_Titolo" id="Attributi_Titolo" class="input-group-field" placeholder="ricerca per titolo">
					    </div>
					    <div class="large-2 medium-2 small-3 cell">
						    <button type="submit" value="cerca" name="cerca" class="button secondary"><i class="fa-duotone fa-magnifying-glass fa-fw"></i></button>
					    </div>
					  </div>
				  </form>
					<form id="formRicerca2" class="formRicerca" method="get" action="/admin/view.aspx">
            <input type="hidden" name="CoreModules_Ky" value="26">
            <input type="hidden" name="CoreEntities_Ky" value="210">
            <input type="hidden" name="CoreGrids_Ky" value="218">
						<div class="grid-x grid-padding-x">
					    <div class="large-2 medium-2 small-3 cell">
					      <label for="Attributi_Descrizione" class="large-text-right small-text-left middle">Descrizione</label>
					    </div>
					    <div class="large-8 medium-8 small-6 cell">
			          <input type="text" name="Attributi_Descrizione" id="Attributi_Descrizione" class="input-group-field" placeholder="ricerca per descrizione">
					    </div>
					    <div class="large-2 medium-2 small-3 cell">
						    <button type="submit" value="cerca" name="cerca" class="button secondary"><i class="fa-duotone fa-magnifying-glass fa-fw"></i></button>
					    </div>
					  </div>
				  </form>
					<form id="formRicerca3" class="formRicerca" method="get" action="/admin/view.aspx">
            <input type="hidden" name="CoreModules_Ky" value="26">
            <input type="hidden" name="CoreEntities_Ky" value="210">
            <input type="hidden" name="CoreGrids_Ky" value="218">
						<div class="grid-x grid-padding-x">
					    <div class="large-2 medium-2 small-3 cell">
					      <label for="Attributi_Codice" class="large-text-right small-text-left middle">Codice</label>
					    </div>
					    <div class="large-8 medium-8 small-6 cell">
			          <input type="text" name="Attributi_Codice" id="Attributi_Codice" class="input-group-field" placeholder="ricerca per codice">
					    </div>
					    <div class="large-2 medium-2 small-3 cell">
						    <button type="submit" value="cerca" name="cerca" class="button secondary"><i class="fa-duotone fa-magnifying-glass fa-fw"></i></button>
					    </div>
					  </div>
				  </form>
			</fieldset>		    
