<fieldset class="filtri fieldset hide hide-for-print" id="filtri" data-toggler=".hide">
<legend>Cerca</legend>
<form id="formRicerca" class="formRicerca" method="get" action="/admin/app/sdk/elenco-CoreAttributes.aspx">
<div class="grid-x grid-padding-x">
<div class="large-2 medium-2 small-4 cell">
<label for="CoreAttributes_Code" class="large-text-right small-text-left middle">Code</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="CoreAttributes_Code" id="CoreAttributes_Code" class="input-group-field" placeholder="ricerca per Code">
</div>
</div>
<div class="grid-x grid-padding-x">
<div class="large-2 medium-2 small-4 cell">
<label for="CoreAttributes_Ky" class="large-text-right small-text-left middle">id</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="CoreAttributes_Ky" id="CoreAttributes_Ky" class="input-group-field" placeholder="ricerca per id">
</div>
</div>
<div class="grid-x grid-padding-x">
<div class="large-12 medium-12 small-12 text-center">
<button type="submit" name="Submit" class="button success"><i class="fa-duotone fa-magnifying-glass fa-fw"></i>Cerca</button>
</div>
</div>
</form>
</fieldset>
