<fieldset class="filtri fieldset hide hide-for-print" id="filtri" data-toggler=".hide">
<legend>Cerca</legend>
<form id="formRicerca" class="formRicerca" method="get" action="/admin/view.aspx">
<input type="hidden" name="CoreModules_Ky" value="29" />
<input type="hidden" name="CoreEntities_Ky" value="122" />
<input type="hidden" name="CoreGrids_Ky" value="143" />
<div class="grid-x grid-padding-x number">
<div class="large-2 medium-2 small-4 cell">
<label for="VeicoliModello_Ky" class="large-text-right small-text-left middle">Codice</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="VeicoliModello_Ky" id="VeicoliModello_Ky" class="input-group-field" placeholder="ricerca per Codice">
</div>
</div>
<div class="grid-x grid-padding-x text">
<div class="large-2 medium-2 small-4 cell">
<label for="VeicoliModello_Titolo" class="large-text-right small-text-left middle">Titolo</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="VeicoliModello_Titolo" id="VeicoliModello_Titolo" class="input-group-field" placeholder="ricerca per Titolo">
</div>
</div>
<div class="grid-x grid-padding-x textarea">
<div class="large-2 medium-2 small-4 cell">
<label for="VeicoliModello_Descrizione" class="large-text-right small-text-left middle">Descrizione</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="VeicoliModello_Descrizione" id="VeicoliModello_Descrizione" class="input-group-field" placeholder="ricerca per Descrizione">
</div>
</div>
<div class="grid-x grid-padding-x join">
<div class="large-2 medium-2 small-4 cell">
<label for="VeicoliMarca_Ky" class="large-text-right small-text-left middle">Marca</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<select name="VeicoliMarca_Ky" id="VeicoliModello_Ky" placeholder="Marca">
<option></option>
<option value="1">
Abarth</option>
<option value="2">
AC</option>
<option value="3">
ACURA</option>
<option value="4">
AIXIAM</option>
<option value="5">
ALFA-ROMEO</option>
<option value="6">
ARIEL</option>
<option value="103">
ARO</option>
<option value="7">
ASIA</option>
<option value="8">
ASTON-MARTIN</option>
<option value="9">
AUDI</option>
<option value="104">
AUSTIN</option>
<option value="10">
AUTOBIANCHI</option>
<option value="11">
BELLIER</option>
<option value="12">
BENTLEY</option>
<option value="13">
BERTONE</option>
<option value="14">
BMW</option>
<option value="15">
BMW-ALPINA</option>
<option value="16">
BRILLIANCE</option>
<option value="17">
BUGATTI</option>
<option value="18">
BUICK</option>
<option value="19">
CADILLAC</option>
<option value="20">
CATERHAM</option>
<option value="21">
CHATENET</option>
<option value="22">
CHEVROLET</option>
<option value="23">
CHRYSLER</option>
<option value="24">
CITROEN</option>
<option value="25">
CONTINENTAL</option>
<option value="26">
CORVETTE</option>
<option value="27">
DACIA</option>
<option value="28">
DAEWOO</option>
<option value="29">
DAF</option>
<option value="30">
DAIHATSU</option>
<option value="31">
DE-LOREAN</option>
<option value="105">
DETOMASO</option>
<option value="32">
DODGE</option>
<option value="33">
DONKERVOORT</option>
<option value="34">
FERRARI</option>
<option value="35">
Fiat</option>
<option value="36">
FORD</option>
<option value="37">
FUN-TECH</option>
<option value="38">
GALLOPER</option>
<option value="39">
GILLET</option>
<option value="40">
GINETTA</option>
<option value="41">
GRECAV</option>
<option value="42">
HONDA</option>
<option value="43">
HUMMER</option>
<option value="44">
HYUNDAI</option>
<option value="45">
INFINITI</option>
<option value="46">
INNOCENTI</option>
<option value="47">
ISUZU</option>
<option value="48">
JAGUAR</option>
<option value="49">
JDM</option>
<option value="50">
JEEP</option>
<option value="51">
KEINATH</option>
<option value="52">
KIA</option>
<option value="53">
LADA</option>
<option value="54">
LAMBORGHINI</option>
<option value="55">
LANCIA</option>
<option value="56">
LAND-ROVER</option>
<option value="57">
LANDWIND</option>
<option value="58">
LEXUS</option>
<option value="59">
LIGIER</option>
<option value="60">
LINCOLN</option>
<option value="61">
LOTUS</option>
<option value="62">
MAHINDRA</option>
<option value="63">
MARCOS</option>
<option value="64">
MASERATI</option>
<option value="65">
MAYBACH</option>
<option value="66">
MAZDA</option>
<option value="67">
MERCEDES-BENZ</option>
<option value="68">
MERCURY</option>
<option value="69">
MG</option>
<option value="70">
MINI</option>
<option value="71">
MITSUBISHI</option>
<option value="106">
MORGAN</option>
<option value="72">
NISSAN</option>
<option value="73">
NOBLE</option>
<option value="74">
OLDSMOBILE</option>
<option value="75">
OPEL</option>
<option value="76">
PAGANI</option>
<option value="77">
PEUGEOT</option>
<option value="78">
PGO</option>
<option value="115">
PIAGGIO</option>
<option value="79">
PLYMOUTH</option>
<option value="111">
POLARIS</option>
<option value="80">
PONTIAC</option>
<option value="81">
PORSCHE</option>
<option value="82">
PROTON</option>
<option value="83">
PUCH</option>
<option value="84">
RENAULT</option>
<option value="85">
ROLLS-ROYCE</option>
<option value="86">
ROVER</option>
<option value="87">
SAAB</option>
<option value="112">
SANTANA</option>
<option value="88">
SEAT</option>
<option value="89">
SKODA</option>
<option value="90">
SMART</option>
<option value="91">
SPYKER</option>
<option value="92">
SSANGYONG</option>
<option value="93">
SUBARU</option>
<option value="94">
SUZUKI</option>
<option value="109">
TALBOT</option>
<option value="95">
TATA</option>
<option value="96">
TOYOTA</option>
<option value="97">
TRABANT</option>
<option value="108">
TVR</option>
<option value="98">
UAZ</option>
<option value="99">
VAUXHALL</option>
<option value="110">
VENTURI</option>
<option value="100">
VOLKSWAGEN</option>
<option value="101">
VOLVO</option>
<option value="113">
WARTBURG</option>
<option value="114">
YES</option>
<option value="102">
ZASTAVA</option>
</select>
</div>
</div>
<div class="grid-x grid-padding-x join">
<div class="large-2 medium-2 small-4 cell">
<label for="VeicoliTipo_Ky" class="large-text-right small-text-left middle">Tipo</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<select name="VeicoliTipo_Ky" id="VeicoliModello_Ky" placeholder="Tipo">
<option></option>
<option value="1">
Auto</option>
<option value="4">
Barche</option>
<option value="3">
Camion</option>
<option value="2">
Moto</option>
</select>
</div>
</div>
<div class="grid-x grid-padding-x join">
<div class="large-2 medium-2 small-4 cell">
<label for="VeicoliCarrozzeria_Ky" class="large-text-right small-text-left middle">Carrozzeria</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<select name="VeicoliCarrozzeria_Ky" id="VeicoliModello_Ky" placeholder="Carrozzeria">
<option></option>
<option value="1">
City Car</option>
<option value="2">
Suv/Fuoristrada</option>
</select>
</div>
</div>
<div class="grid-x grid-padding-x checkbox">
<div class="large-2 medium-2 small-4 cell">
<label for="VeicoliModello_Km0" class="large-text-right small-text-left middle">Km0</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="checkbox" name="VeicoliModello_Km0" id="VeicoliModello_Km0" class="input-group-field" placeholder="ricerca per Km0" value="1">
</div>
</div>
<div class="grid-x grid-padding-x checkbox">
<div class="large-2 medium-2 small-4 cell">
<label for="VeicoliModello_Usato" class="large-text-right small-text-left middle">Usato</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="checkbox" name="VeicoliModello_Usato" id="VeicoliModello_Usato" class="input-group-field" placeholder="ricerca per Usato" value="1">
</div>
</div>
<div class="grid-x grid-padding-x">
<div class="large-12 medium-12 small-12 text-center">
<button type="submit" name="Submit" class="button success"><i class="fa-duotone fa-magnifying-glass fa-fw"></i>Cerca</button>
</div>
</div>
</form>
</fieldset>
