<fieldset class="filtri fieldset hide hide-for-print" id="filtri" data-toggler=".hide">
<legend>Cerca</legend>
<form id="formRicerca" class="formRicerca" method="get" action="/admin/view.aspx">
<input type="hidden" name="CoreModules_Ky" value="12" />
<input type="hidden" name="CoreEntities_Ky" value="165" />
<input type="hidden" name="CoreGrids_Ky" value="22" />
<div class="grid-x grid-padding-x number">
<div class="large-2 medium-2 small-4 cell">
<label for="UtentiLog_Ky" class="large-text-right small-text-left middle">Ky</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="UtentiLog_Ky" id="UtentiLog_Ky" class="input-group-field" placeholder="ricerca per Ky">
</div>
</div>
<div class="grid-x grid-padding-x join">
<div class="large-2 medium-2 small-4 cell">
<label for="Utenti_Ky" class="large-text-right small-text-left middle">Utente</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<select name="Utenti_Ky" id="UtentiLog_Ky" placeholder="Utente">
<option></option>
<option value="1">
1 - info@rswstudio.it</option>
<option value="2">
2 - matteo.testoni@rswstudio.it</option>
<option value="3">
3 - mattia.gazzabin@rswstudio.it</option>
<option value="4">
4 - gianluca.milan@rswstudio.it</option>
<option value="5">
5 - vanessa.garani@rswstudio.it</option>
<option value="6">
6 - matteo.altieri@rswstudio.it</option>
<option value="7">
7 - francesca.lamalfa@rswstudio.it</option>
<option value="8">
8 - social@rswstudio.it</option>
<option value="9">
9 - amministrazione@rswstudio.it</option>
<option value="10">
10 - nico.bondesan@rswstudio.it</option>
<option value="11">
11 - mattia.mazzaro@rswstudio.it</option>
<option value="12">
12 - elisa.cucco@rswstudio.it</option>
<option value="13">
13 - serman.nerjaku@into-deep.com</option>
<option value="14">
14 - alessandro.bonini@rswstudio.it</option>
<option value="15">
15 - patrizia.blue92@gmail.com</option>
<option value="16">
16 - elena.cugola@rswstudio.it</option>
<option value="17">
17 - irene.gozzo@rswstudio.it</option>
<option value="18">
18 - antonino.merlo@rswstudio.it</option>
<option value="20">
20 - ilaria.zilli@rswstudio.it</option>
<option value="21">
21 - sofia.ghirardello@rswstudio.it</option>
</select>
</div>
</div>
<div class="grid-x grid-padding-x">
<div class="large-12 medium-12 small-12 text-center">
<button type="submit" name="Submit" class="button success"><i class="fa-duotone fa-magnifying-glass fa-fw"></i>Cerca</button>
</div>
</div>
</form>
</fieldset>
