<fieldset class="filtri fieldset hide hide-for-print" id="filtri" data-toggler=".hide">
<legend>Cerca</legend>
<form id="formRicerca" class="formRicerca" method="get" action="/admin/view.aspx">
<input type="hidden" name="CoreModules_Ky" value="12" />
<input type="hidden" name="CoreEntities_Ky" value="9" />
<input type="hidden" name="CoreGrids_Ky" value="10" />
<div class="grid-x grid-padding-x number">
<div class="large-2 medium-2 small-4 cell">
<label for="Lingue_Ky" class="large-text-right small-text-left middle">id</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="Lingue_Ky" id="Lingue_Ky" class="input-group-field" placeholder="ricerca per id">
</div>
</div>
<div class="grid-x grid-padding-x text">
<div class="large-2 medium-2 small-4 cell">
<label for="Lingue_Titolo" class="large-text-right small-text-left middle">Titolo</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="Lingue_Titolo" id="Lingue_Titolo" class="input-group-field" placeholder="ricerca per Titolo">
</div>
</div>
<div class="grid-x grid-padding-x join">
<div class="large-2 medium-2 small-4 cell">
<label for="Divise_Ky" class="large-text-right small-text-left middle">Divisa</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<select name="Divise_Ky" id="Lingue_Ky" placeholder="Divisa">
<option></option>
<option value="5">
Afghani</option>
<option value="6">
Ariary Malgascio</option>
<option value="7">
Baht Tailandese</option>
<option value="8">
Balboa di Panama</option>
<option value="9">
Birr Etiopico</option>
<option value="12">
Bolívar Venezuelano</option>
<option value="10">
Bolivar Venezuelano (1871–2008)</option>
<option value="11">
Boliviano</option>
<option value="13">
Cedi ghanese</option>
<option value="14">
Colón Costaricano</option>
<option value="15">
Colón Salvadoregno</option>
<option value="16">
Cordoba Nicaraguense</option>
<option value="17">
Corona Ceca</option>
<option value="18">
Corona Danese</option>
<option value="23">
Corona dell’Estonia</option>
<option value="19">
Corona Islandese</option>
<option value="20">
Corona Norvegese</option>
<option value="21">
Corona Slovacca</option>
<option value="22">
Corona Svedese</option>
<option value="24">
Dalasi del Gambia</option>
<option value="25">
Dinaro Algerino</option>
<option value="33">
Dinaro del Bahraini</option>
<option value="26">
Dinaro Giordano</option>
<option value="27">
Dinaro Iracheno</option>
<option value="28">
Dinaro Kuwaitiano</option>
<option value="29">
Dinaro Libico</option>
<option value="30">
Dinaro Macedone</option>
<option value="31">
Dinaro Serbo</option>
<option value="32">
Dinaro Tunisino</option>
<option value="35">
Dirham degli Emirati Arabi Uniti</option>
<option value="34">
Dirham Marocchino</option>
<option value="36">
Dobra di Sao Tomé e Principe</option>
<option value="37">
Dollaro Australiano</option>
<option value="38">
Dollaro Canadese</option>
<option value="45">
Dollaro dei Caraibi Orientali</option>
<option value="46">
Dollaro del Belize</option>
<option value="47">
Dollaro del Brunei</option>
<option value="48">
Dollaro della Guyana</option>
<option value="49">
Dollaro della Rhodesia</option>
<option value="50">
Dollaro delle Bahamas</option>
<option value="51">
Dollaro delle Bermuda</option>
<option value="52">
Dollaro delle Figi</option>
<option value="53">
Dollaro delle Isole Cayman</option>
<option value="54">
Dollaro delle Isole Solomon</option>
<option value="55">
Dollaro dello Zimbabwe</option>
<option value="56">
Dollaro di Barbados</option>
<option value="57">
Dollaro di Hong Kong</option>
<option value="58">
Dollaro di Singapore</option>
<option value="59">
Dollaro di Trinidad e Tobago</option>
<option value="39">
Dollaro Giamaicano</option>
<option value="40">
Dollaro Liberiano</option>
<option value="41">
Dollaro Namibiano</option>
<option value="42">
Dollaro Neozelandese</option>
<option value="43">
Dollaro Statunitense</option>
<option value="44">
Dollaro Surinamese</option>
<option value="60">
Dong Vietnamita</option>
<option value="61">
Dram Armeno</option>
<option value="62">
Ekwele della Guinea Equatoriale</option>
<option value="63">
Escudo del Capo Verde</option>
<option value="64">
Euro</option>
<option value="66">
Fiorino delle Antille Olandesi</option>
<option value="67">
Fiorino di Aruba</option>
<option value="65">
Fiorino Ungherese</option>
<option value="68">
Franco CFA BCEAO</option>
<option value="69">
Franco CFP</option>
<option value="70">
Franco Comoriano</option>
<option value="71">
Franco Congolese</option>
<option value="75">
Franco del Burundi</option>
<option value="76">
Franco della Guinea</option>
<option value="72">
Franco Gibutiano</option>
<option value="73">
Franco Ruandese</option>
<option value="74">
Franco Svizzero</option>
<option value="77">
Gourde Haitiano</option>
<option value="78">
Grivnia Ucraina</option>
<option value="79">
Guaraní del Paraguay</option>
<option value="80">
Kina della Papua Nuova Guinea</option>
<option value="81">
Kip Laotiano</option>
<option value="82">
Kuna Croata</option>
<option value="83">
Kupon Larit Georgiano</option>
<option value="85">
Kwacha dello Zambia (1968–2012)</option>
<option value="84">
Kwacha Malawiano</option>
<option value="86">
Kwanza Angolano</option>
<option value="87">
Kyat Birmano</option>
<option value="88">
Kyat di Myanmar</option>
<option value="89">
Lari Georgiano</option>
<option value="90">
Lats Lettone</option>
<option value="91">
Lek Albanese</option>
<option value="92">
Lempira Honduregna</option>
<option value="93">
Leone della Sierra Leone</option>
<option value="96">
Leu della Romania</option>
<option value="94">
Leu Moldavo</option>
<option value="95">
Leu Rumeno</option>
<option value="97">
Lilangeni dello Swaziland</option>
<option value="98">
Lira Turca</option>
<option value="99">
Litas Lituano</option>
<option value="100">
Loti del Lesotho</option>
<option value="101">
Manat Azero</option>
<option value="102">
Manat Azero (1993–2006)</option>
<option value="103">
Manat Turkmeno (1993–2009)</option>
<option value="104">
Marco Conv. Bosnia-Erzegovina</option>
<option value="105">
Metical mozambicano</option>
<option value="106">
Naira Nigeriana</option>
<option value="107">
Nakfa Eritreo</option>
<option value="108">
Ngultrum Butanese</option>
<option value="109">
Nuova Lira Turca</option>
<option value="112">
Nuovo dollaro taiwanese</option>
<option value="110">
Nuovo Lev Bulgaro</option>
<option value="111">
Nuovo Shequel Israeliano</option>
<option value="113">
Ouguiya della Mauritania</option>
<option value="115">
Pa?anga di Tonga</option>
<option value="114">
Pataca di Macao</option>
<option value="116">
Peso Argentino</option>
<option value="117">
Peso Cileno</option>
<option value="118">
Peso Colombiano</option>
<option value="119">
Peso Cubano</option>
<option value="123">
Peso delle Filippine</option>
<option value="120">
Peso Dominicano</option>
<option value="121">
Peso Messicano</option>
<option value="122">
Peso Uruguaiano</option>
<option value="124">
Pula del Botswana</option>
<option value="125">
Quetzal Guatemalteco</option>
<option value="126">
Rand Sudafricano</option>
<option value="127">
Real Brasiliano</option>
<option value="128">
Renmimbi Cinese</option>
<option value="130">
Rial del Qatar</option>
<option value="132">
Rial dello Yemen</option>
<option value="131">
Rial dell'Oman</option>
<option value="129">
Rial Iraniano</option>
<option value="133">
Riel Cambogiano</option>
<option value="134">
Ringgit della Malesia</option>
<option value="135">
Rublo Bielorussia</option>
<option value="136">
Rublo Russo</option>
<option value="137">
Rufiyaa delle Maldive</option>
<option value="142">
Rupia del Pakistan</option>
<option value="143">
Rupia delle Seychelles</option>
<option value="144">
Rupia di Sri Lanka</option>
<option value="138">
Rupia Indiana</option>
<option value="139">
Rupia Indonesiana</option>
<option value="140">
Rupia Mauriziana</option>
<option value="141">
Rupia Nepalese</option>
<option value="145">
Ryal Saudita</option>
<option value="149">
Scellino della Tanzania</option>
<option value="146">
Scellino Keniota</option>
<option value="147">
Scellino Somalo</option>
<option value="148">
Scellino Ugandese</option>
<option value="150">
Sol Nuevo Peruviano</option>
<option value="151">
Som Kirghiso</option>
<option value="152">
Somoni del Tajikistan</option>
<option value="158">
Sterlina delle Falkland</option>
<option value="159">
Sterlina di Gibilterra</option>
<option value="160">
Sterlina di Sant’Elena</option>
<option value="153">
Sterlina Egiziana</option>
<option value="154">
Sterlina Inglese</option>
<option value="155">
Sterlina Libanese</option>
<option value="156">
Sterlina Siriana</option>
<option value="157">
Sterlina Sudanese</option>
<option value="161">
Sum dell’Uzbekistan</option>
<option value="162">
Taka Bangladese</option>
<option value="163">
Tala della Samoa Occidentale</option>
<option value="164">
Tenge Kazaco</option>
<option value="165">
Tugrik Mongolo</option>
<option value="166">
Vatu di Vanuatu</option>
<option value="167">
Won Nordcoreano</option>
<option value="168">
Won Sudcoreano</option>
<option value="169">
Yen Giapponese</option>
<option value="170">
Zloty Polacco</option>
</select>
</div>
</div>
<div class="grid-x grid-padding-x text">
<div class="large-2 medium-2 small-4 cell">
<label for="Lingue_Codice" class="large-text-right small-text-left middle">Codice</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="Lingue_Codice" id="Lingue_Codice" class="input-group-field" placeholder="ricerca per Codice">
</div>
</div>
<div class="grid-x grid-padding-x">
<div class="large-12 medium-12 small-12 text-center">
<button type="submit" name="Submit" class="button success"><i class="fa-duotone fa-magnifying-glass fa-fw"></i>Cerca</button>
</div>
</div>
</form>
</fieldset>
