<fieldset class="filtri fieldset hide hide-for-print" id="filtri" data-toggler=".hide">
<legend>Cerca</legend>
<form id="formRicerca" class="formRicerca" method="get" action="/admin/view.aspx">
<input type="hidden" name="CoreModules_Ky" value="12" />
<input type="hidden" name="CoreEntities_Ky" value="5" />
<input type="hidden" name="CoreGrids_Ky" value="6" />
<div class="grid-x grid-padding-x number">
<div class="large-2 medium-2 small-4 cell">
<label for="Nazioni_Ky" class="large-text-right small-text-left middle">id</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="Nazioni_Ky" id="Nazioni_Ky" class="input-group-field" placeholder="ricerca per id">
</div>
</div>
<div class="grid-x grid-padding-x text">
<div class="large-2 medium-2 small-4 cell">
<label for="Nazioni_Nazione" class="large-text-right small-text-left middle">Nazione</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="Nazioni_Nazione" id="Nazioni_Nazione" class="input-group-field" placeholder="ricerca per Nazione">
</div>
</div>
<div class="grid-x grid-padding-x text">
<div class="large-2 medium-2 small-4 cell">
<label for="Nazioni_Codice" class="large-text-right small-text-left middle">Codice</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="Nazioni_Codice" id="Nazioni_Codice" class="input-group-field" placeholder="ricerca per Codice">
</div>
</div>
<div class="grid-x grid-padding-x checkbox">
<div class="large-2 medium-2 small-4 cell">
<label for="Nazioni_UE" class="large-text-right small-text-left middle">UE</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="checkbox" name="Nazioni_UE" id="Nazioni_UE" class="input-group-field" placeholder="ricerca per UE" value="1">
</div>
</div>
<div class="grid-x grid-padding-x join">
<div class="large-2 medium-2 small-4 cell">
<label for="TimeZones_Ky" class="large-text-right small-text-left middle">id</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<select name="TimeZones_Ky" id="Nazioni_Ky" placeholder="id">
<option></option>
<option value="1">
1 - Africa/Abidjan</option>
<option value="2">
2 - Africa/Accra</option>
<option value="3">
3 - Africa/Addis_Ababa</option>
<option value="4">
4 - Africa/Algiers</option>
<option value="5">
5 - Africa/Asmara</option>
<option value="6">
6 - Africa/Asmera</option>
<option value="7">
7 - Africa/Bamako</option>
<option value="8">
8 - Africa/Lagos|Africa/Bangui</option>
<option value="9">
9 - Africa/Banjul</option>
<option value="10">
10 - Africa/Bissau</option>
<option value="11">
11 - Africa/Blantyre</option>
<option value="12">
12 - Africa/Brazzaville</option>
<option value="13">
13 - Africa/Bujumbura</option>
<option value="14">
14 - Africa/Cairo</option>
<option value="15">
15 - Africa/Casablanca</option>
<option value="16">
16 - Africa/Ceuta</option>
<option value="17">
17 - Africa/Conakry</option>
<option value="18">
18 - Africa/Dakar</option>
<option value="19">
19 - Africa/Dar_es_Salaam</option>
<option value="20">
20 - Africa/Djibouti</option>
<option value="21">
21 - Africa/Douala</option>
<option value="22">
22 - Africa/El_Aaiun</option>
<option value="23">
23 - Africa/Freetown</option>
<option value="24">
24 - Africa/Gaborone</option>
<option value="25">
25 - Africa/Harare</option>
<option value="26">
26 - Africa/Johannesburg</option>
<option value="27">
27 - Africa/Juba</option>
<option value="28">
28 - Africa/Kampala</option>
<option value="29">
29 - Africa/Khartoum</option>
<option value="30">
30 - Africa/Kigali</option>
<option value="31">
31 - Africa/Kinshasa</option>
<option value="32">
32 - Africa/Lagos</option>
<option value="33">
33 - Africa/Libreville</option>
<option value="34">
34 - Africa/Lome</option>
<option value="35">
35 - Africa/Luanda</option>
<option value="36">
36 - Africa/Lubumbashi</option>
<option value="37">
37 - Africa/Lusaka</option>
<option value="38">
38 - Africa/Malabo</option>
<option value="39">
39 - Africa/Maputo</option>
<option value="40">
40 - Africa/Maseru</option>
<option value="41">
41 - Africa/Mbabane</option>
<option value="42">
42 - Africa/Mogadishu</option>
<option value="43">
43 - Africa/Monrovia</option>
<option value="44">
44 - Africa/Nairobi</option>
<option value="45">
45 - Africa/Ndjamena</option>
<option value="46">
46 - Africa/Niamey</option>
<option value="47">
47 - Africa/Nouakchott</option>
<option value="48">
48 - Africa/Ouagadougou</option>
<option value="49">
49 - Africa/Porto-Novo</option>
<option value="50">
50 - Africa/Sao_Tome</option>
<option value="51">
51 - Africa/Timbuktu</option>
<option value="52">
52 - Africa/Tripoli</option>
<option value="53">
53 - Africa/Tunis</option>
<option value="54">
54 - Africa/Windhoek</option>
<option value="55">
55 - America/Adak</option>
<option value="56">
56 - America/Anchorage</option>
<option value="57">
57 - America/Anguilla</option>
<option value="58">
58 - America/Antigua</option>
<option value="59">
59 - America/Araguaina</option>
<option value="60">
60 - America/Argentina/Buenos_Aires</option>
<option value="61">
61 - America/Argentina/Catamarca</option>
<option value="62">
62 - America/Argentina/ComodRivadavia</option>
<option value="63">
63 - America/Argentina/Cordoba</option>
<option value="64">
64 - America/Argentina/Jujuy</option>
<option value="65">
65 - America/Argentina/La_Rioja</option>
<option value="66">
66 - America/Argentina/Mendoza</option>
<option value="67">
67 - America/Argentina/Rio_Gallegos</option>
<option value="68">
68 - America/Argentina/Salta</option>
<option value="69">
69 - America/Argentina/San_Juan</option>
<option value="70">
70 - America/Argentina/San_Luis</option>
<option value="71">
71 - America/Argentina/Tucuman</option>
<option value="72">
72 - America/Argentina/Ushuaia</option>
<option value="73">
73 - America/Aruba</option>
<option value="74">
74 - America/Asuncion</option>
<option value="75">
75 - America/Atikokan</option>
<option value="76">
76 - America/Atka</option>
<option value="77">
77 - America/Bahia</option>
<option value="78">
78 - America/Bahia_Banderas</option>
<option value="79">
79 - America/Barbados</option>
<option value="80">
80 - America/Belem</option>
<option value="81">
81 - America/Belize</option>
<option value="82">
82 - America/Blanc-Sablon</option>
<option value="83">
83 - America/Boa_Vista</option>
<option value="84">
84 - America/Bogota</option>
<option value="85">
85 - America/Boise</option>
<option value="86">
86 - America/Buenos_Aires</option>
<option value="87">
87 - America/Cambridge_Bay</option>
<option value="88">
88 - America/Campo_Grande</option>
<option value="89">
89 - America/Cancun</option>
<option value="90">
90 - America/Caracas</option>
<option value="91">
91 - America/Catamarca</option>
<option value="92">
92 - America/Cayenne</option>
<option value="93">
93 - America/Cayman</option>
<option value="94">
94 - America/Chicago</option>
<option value="95">
95 - America/Chihuahua</option>
<option value="96">
96 - America/Coral_Harbour</option>
<option value="97">
97 - America/Cordoba</option>
<option value="98">
98 - America/Costa_Rica</option>
<option value="99">
99 - America/Creston</option>
<option value="100">
100 - America/Cuiaba</option>
<option value="101">
101 - America/Curacao</option>
<option value="102">
102 - America/Danmarkshavn</option>
<option value="103">
103 - America/Dawson</option>
<option value="104">
104 - America/Dawson_Creek</option>
<option value="105">
105 - America/Denver</option>
<option value="106">
106 - America/Detroit</option>
<option value="107">
107 - America/Dominica</option>
<option value="108">
108 - America/Edmonton</option>
<option value="109">
109 - America/Eirunepe</option>
<option value="110">
110 - America/El_Salvador</option>
<option value="111">
111 - America/Ensenada</option>
<option value="112">
112 - America/Fort_Nelson</option>
<option value="113">
113 - America/Fort_Wayne</option>
<option value="114">
114 - America/Fortaleza</option>
<option value="115">
115 - America/Glace_Bay</option>
<option value="116">
116 - America/Godthab</option>
<option value="117">
117 - America/Goose_Bay</option>
<option value="118">
118 - America/Grand_Turk</option>
<option value="119">
119 - America/Grenada</option>
<option value="120">
120 - America/Guadeloupe</option>
<option value="121">
121 - America/Guatemala</option>
<option value="122">
122 - America/Guayaquil</option>
<option value="123">
123 - America/Guyana</option>
<option value="124">
124 - America/Halifax</option>
<option value="125">
125 - America/Havana</option>
<option value="126">
126 - America/Hermosillo</option>
<option value="127">
127 - America/Indiana/Indianapolis</option>
<option value="128">
128 - America/Indiana/Knox</option>
<option value="129">
129 - America/Indiana/Marengo</option>
<option value="130">
130 - America/Indiana/Petersburg</option>
<option value="131">
131 - America/Indiana/Tell_City</option>
<option value="132">
132 - America/Indiana/Vevay</option>
<option value="133">
133 - America/Indiana/Vincennes</option>
<option value="134">
134 - America/Indiana/Winamac</option>
<option value="135">
135 - America/Indianapolis</option>
<option value="136">
136 - America/Inuvik</option>
<option value="137">
137 - America/Iqaluit</option>
<option value="138">
138 - America/Jamaica</option>
<option value="139">
139 - America/Jujuy</option>
<option value="140">
140 - America/Juneau</option>
<option value="141">
141 - America/Kentucky/Louisville</option>
<option value="142">
142 - America/Kentucky/Monticello</option>
<option value="143">
143 - America/Knox_IN</option>
<option value="144">
144 - America/Kralendijk</option>
<option value="145">
145 - America/La_Paz</option>
<option value="146">
146 - America/Lima</option>
<option value="147">
147 - America/Los_Angeles</option>
<option value="148">
148 - America/Louisville</option>
<option value="149">
149 - America/Lower_Princes</option>
<option value="150">
150 - America/Maceio</option>
<option value="151">
151 - America/Managua</option>
<option value="152">
152 - America/Manaus</option>
<option value="153">
153 - America/Marigot</option>
<option value="154">
154 - America/Martinique</option>
<option value="155">
155 - America/Matamoros</option>
<option value="156">
156 - America/Mazatlan</option>
<option value="157">
157 - America/Mendoza</option>
<option value="158">
158 - America/Menominee</option>
<option value="159">
159 - America/Merida</option>
<option value="160">
160 - America/Metlakatla</option>
<option value="161">
161 - America/Mexico_City</option>
<option value="162">
162 - America/Miquelon</option>
<option value="163">
163 - America/Moncton</option>
<option value="164">
164 - America/Monterrey</option>
<option value="165">
165 - America/Montevideo</option>
<option value="166">
166 - America/Montreal</option>
<option value="167">
167 - America/Montserrat</option>
<option value="168">
168 - America/Nassau</option>
<option value="169">
169 - America/New_York</option>
<option value="170">
170 - America/Nipigon</option>
<option value="171">
171 - America/Nome</option>
<option value="172">
172 - America/Noronha</option>
<option value="173">
173 - America/North_Dakota/Beulah</option>
<option value="174">
174 - America/North_Dakota/Center</option>
<option value="175">
175 - America/North_Dakota/New_Salem</option>
<option value="176">
176 - America/Ojinaga</option>
<option value="177">
177 - America/Panama</option>
<option value="178">
178 - America/Pangnirtung</option>
<option value="179">
179 - America/Paramaribo</option>
<option value="180">
180 - America/Phoenix</option>
<option value="181">
181 - America/Port_of_Spain</option>
<option value="182">
182 - America/Port-au-Prince</option>
<option value="183">
183 - America/Porto_Acre</option>
<option value="184">
184 - America/Porto_Velho</option>
<option value="185">
185 - America/Puerto_Rico</option>
<option value="186">
186 - America/Punta_Arenas</option>
<option value="187">
187 - America/Rainy_River</option>
<option value="188">
188 - America/Rankin_Inlet</option>
<option value="189">
189 - America/Recife</option>
<option value="190">
190 - America/Regina</option>
<option value="191">
191 - America/Resolute</option>
<option value="192">
192 - America/Rio_Branco</option>
<option value="193">
193 - America/Rosario</option>
<option value="194">
194 - America/Santa_Isabel</option>
<option value="195">
195 - America/Santarem</option>
<option value="196">
196 - America/Santiago</option>
<option value="197">
197 - America/Santo_Domingo</option>
<option value="198">
198 - America/Sao_Paulo</option>
<option value="199">
199 - America/Scoresbysund</option>
<option value="200">
200 - America/Shiprock</option>
<option value="201">
201 - America/Sitka</option>
<option value="202">
202 - America/St_Barthelemy</option>
<option value="203">
203 - America/St_Johns</option>
<option value="204">
204 - America/St_Kitts</option>
<option value="205">
205 - America/St_Lucia</option>
<option value="206">
206 - America/St_Thomas</option>
<option value="207">
207 - America/St_Vincent</option>
<option value="208">
208 - America/Swift_Current</option>
<option value="209">
209 - America/Tegucigalpa</option>
<option value="210">
210 - America/Thule</option>
<option value="211">
211 - America/Thunder_Bay</option>
<option value="212">
212 - America/Tijuana</option>
<option value="213">
213 - America/Toronto</option>
<option value="214">
214 - America/Tortola</option>
<option value="215">
215 - America/Vancouver</option>
<option value="216">
216 - America/Virgin</option>
<option value="217">
217 - America/Whitehorse</option>
<option value="218">
218 - America/Winnipeg</option>
<option value="219">
219 - America/Yakutat</option>
<option value="220">
220 - America/Yellowknife</option>
<option value="221">
221 - Antarctica/Casey</option>
<option value="222">
222 - Antarctica/Davis</option>
<option value="223">
223 - Antarctica/DumontDUrville</option>
<option value="224">
224 - Antarctica/Macquarie</option>
<option value="225">
225 - Antarctica/Mawson</option>
<option value="226">
226 - Antarctica/McMurdo</option>
<option value="227">
227 - Antarctica/Palmer</option>
<option value="228">
228 - Antarctica/Rothera</option>
<option value="229">
229 - Antarctica/South_Pole</option>
<option value="230">
230 - Antarctica/Syowa</option>
<option value="231">
231 - Antarctica/Troll</option>
<option value="232">
232 - Antarctica/Vostok</option>
<option value="233">
233 - Arctic/Longyearbyen</option>
<option value="234">
234 - Asia/Aden</option>
<option value="235">
235 - Asia/Almaty</option>
<option value="236">
236 - Asia/Amman</option>
<option value="237">
237 - Asia/Anadyr</option>
<option value="238">
238 - Asia/Aqtau</option>
<option value="239">
239 - Asia/Aqtobe</option>
<option value="240">
240 - Asia/Ashgabat</option>
<option value="241">
241 - Asia/Ashkhabad</option>
<option value="242">
242 - Asia/Atyrau</option>
<option value="243">
243 - Asia/Baghdad</option>
<option value="244">
244 - Asia/Bahrain</option>
<option value="245">
245 - Asia/Baku</option>
<option value="246">
246 - Asia/Bangkok</option>
<option value="247">
247 - Asia/Barnaul</option>
<option value="248">
248 - Asia/Beirut</option>
<option value="249">
249 - Asia/Bishkek</option>
<option value="250">
250 - Asia/Brunei</option>
<option value="251">
251 - Asia/Calcutta</option>
<option value="252">
252 - Asia/Chita</option>
<option value="253">
253 - Asia/Choibalsan</option>
<option value="254">
254 - Asia/Chongqing</option>
<option value="255">
255 - Asia/Chungking</option>
<option value="256">
256 - Asia/Colombo</option>
<option value="257">
257 - Asia/Dacca</option>
<option value="258">
258 - Asia/Damascus</option>
<option value="259">
259 - Asia/Dhaka</option>
<option value="260">
260 - Asia/Dili</option>
<option value="261">
261 - Asia/Dubai</option>
<option value="262">
262 - Asia/Dushanbe</option>
<option value="263">
263 - Asia/Famagusta</option>
<option value="264">
264 - Asia/Gaza</option>
<option value="265">
265 - Asia/Harbin</option>
<option value="266">
266 - Asia/Hebron</option>
<option value="267">
267 - Asia/Ho_Chi_Minh</option>
<option value="268">
268 - Asia/Hong_Kong</option>
<option value="269">
269 - Asia/Hovd</option>
<option value="270">
270 - Asia/Irkutsk</option>
<option value="271">
271 - Asia/Istanbul</option>
<option value="272">
272 - Asia/Jakarta</option>
<option value="273">
273 - Asia/Jayapura</option>
<option value="274">
274 - Asia/Jerusalem</option>
<option value="275">
275 - Asia/Kabul</option>
<option value="276">
276 - Asia/Kamchatka</option>
<option value="277">
277 - Asia/Karachi</option>
<option value="278">
278 - Asia/Kashgar</option>
<option value="279">
279 - Asia/Kathmandu</option>
<option value="280">
280 - Asia/Katmandu</option>
<option value="281">
281 - Asia/Khandyga</option>
<option value="282">
282 - Asia/Kolkata</option>
<option value="283">
283 - Asia/Krasnoyarsk</option>
<option value="284">
284 - Asia/Kuala_Lumpur</option>
<option value="285">
285 - Asia/Kuching</option>
<option value="286">
286 - Asia/Kuwait</option>
<option value="287">
287 - Asia/Macao</option>
<option value="288">
288 - Asia/Macau</option>
<option value="289">
289 - Asia/Magadan</option>
<option value="290">
290 - Asia/Makassar</option>
<option value="291">
291 - Asia/Manila</option>
<option value="292">
292 - Asia/Muscat</option>
<option value="293">
293 - Asia/Nicosia</option>
<option value="294">
294 - Asia/Novokuznetsk</option>
<option value="295">
295 - Asia/Novosibirsk</option>
<option value="296">
296 - Asia/Omsk</option>
<option value="297">
297 - Asia/Oral</option>
<option value="298">
298 - Asia/Phnom_Penh</option>
<option value="299">
299 - Asia/Pontianak</option>
<option value="300">
300 - Asia/Pyongyang</option>
<option value="301">
301 - Asia/Qatar</option>
<option value="302">
302 - Asia/Qyzylorda</option>
<option value="303">
303 - Asia/Rangoon</option>
<option value="304">
304 - Asia/Riyadh</option>
<option value="305">
305 - Asia/Saigon</option>
<option value="306">
306 - Asia/Sakhalin</option>
<option value="307">
307 - Asia/Samarkand</option>
<option value="308">
308 - Asia/Seoul</option>
<option value="309">
309 - Asia/Shanghai</option>
<option value="310">
310 - Asia/Singapore</option>
<option value="311">
311 - Asia/Srednekolymsk</option>
<option value="312">
312 - Asia/Taipei</option>
<option value="313">
313 - Asia/Tashkent</option>
<option value="314">
314 - Asia/Tbilisi</option>
<option value="315">
315 - Asia/Tehran</option>
<option value="316">
316 - Asia/Tel_Aviv</option>
<option value="317">
317 - Asia/Thimbu</option>
<option value="318">
318 - Asia/Thimphu</option>
<option value="319">
319 - Asia/Tokyo</option>
<option value="320">
320 - Asia/Tomsk</option>
<option value="321">
321 - Asia/Ujung_Pandang</option>
<option value="322">
322 - Asia/Ulaanbaatar</option>
<option value="323">
323 - Asia/Ulan_Bator</option>
<option value="324">
324 - Asia/Urumqi</option>
<option value="325">
325 - Asia/Ust-Nera</option>
<option value="326">
326 - Asia/Vientiane</option>
<option value="327">
327 - Asia/Vladivostok</option>
<option value="328">
328 - Asia/Yakutsk</option>
<option value="329">
329 - Asia/Yangon</option>
<option value="330">
330 - Asia/Yekaterinburg</option>
<option value="331">
331 - Asia/Yerevan</option>
<option value="332">
332 - Atlantic/Azores</option>
<option value="333">
333 - Atlantic/Bermuda</option>
<option value="334">
334 - Atlantic/Canary</option>
<option value="335">
335 - Atlantic/Cape_Verde</option>
<option value="336">
336 - Atlantic/Faeroe</option>
<option value="337">
337 - Atlantic/Faroe</option>
<option value="338">
338 - Atlantic/Jan_Mayen</option>
<option value="339">
339 - Atlantic/Madeira</option>
<option value="340">
340 - Atlantic/Reykjavik</option>
<option value="341">
341 - Atlantic/South_Georgia</option>
<option value="342">
342 - Atlantic/St_Helena</option>
<option value="343">
343 - Atlantic/Stanley</option>
<option value="344">
344 - Australia/ACT</option>
<option value="345">
345 - Australia/Adelaide</option>
<option value="346">
346 - Australia/Brisbane</option>
<option value="347">
347 - Australia/Broken_Hill</option>
<option value="348">
348 - Australia/Canberra</option>
<option value="349">
349 - Australia/Currie</option>
<option value="350">
350 - Australia/Darwin</option>
<option value="351">
351 - Australia/Eucla</option>
<option value="352">
352 - Australia/Hobart</option>
<option value="353">
353 - Australia/LHI</option>
<option value="354">
354 - Australia/Lindeman</option>
<option value="355">
355 - Australia/Lord_Howe</option>
<option value="356">
356 - Australia/Melbourne</option>
<option value="357">
357 - Australia/North</option>
<option value="358">
358 - Australia/NSW</option>
<option value="359">
359 - Australia/Perth</option>
<option value="360">
360 - Australia/Queensland</option>
<option value="361">
361 - Australia/South</option>
<option value="362">
362 - Australia/Sydney</option>
<option value="363">
363 - Australia/Tasmania</option>
<option value="364">
364 - Australia/Victoria</option>
<option value="365">
365 - Australia/West</option>
<option value="366">
366 - Australia/Yancowinna</option>
<option value="367">
367 - Brazil/Acre</option>
<option value="368">
368 - Brazil/DeNoronha</option>
<option value="369">
369 - Brazil/East</option>
<option value="370">
370 - Brazil/West</option>
<option value="371">
371 - Canada/Atlantic</option>
<option value="372">
372 - Canada/Central</option>
<option value="373">
373 - Canada/Eastern</option>
<option value="374">
374 - Canada/Mountain</option>
<option value="375">
375 - Canada/Newfoundland</option>
<option value="376">
376 - Canada/Pacific</option>
<option value="377">
377 - Canada/Saskatchewan</option>
<option value="378">
378 - Canada/Yukon</option>
<option value="379">
379 - CET</option>
<option value="380">
380 - Chile/Continental</option>
<option value="381">
381 - Chile/EasterIsland</option>
<option value="382">
382 - CST6CDT</option>
<option value="383">
383 - Cuba</option>
<option value="384">
384 - EET</option>
<option value="385">
385 - Egypt</option>
<option value="386">
386 - Eire</option>
<option value="387">
387 - EST</option>
<option value="388">
388 - EST5EDT</option>
<option value="389">
389 - Etc/GMT</option>
<option value="390">
390 - Etc/GMT+0</option>
<option value="391">
391 - Etc/GMT+1</option>
<option value="392">
392 - Etc/GMT+10</option>
<option value="393">
393 - Etc/GMT+11</option>
<option value="394">
394 - Etc/GMT+12</option>
<option value="395">
395 - Etc/GMT+2</option>
<option value="396">
396 - Etc/GMT+3</option>
<option value="397">
397 - Etc/GMT+4</option>
<option value="398">
398 - Etc/GMT+5</option>
<option value="399">
399 - Etc/GMT+6</option>
<option value="400">
400 - Etc/GMT+7</option>
<option value="401">
401 - Etc/GMT+8</option>
<option value="402">
402 - Etc/GMT+9</option>
<option value="403">
403 - Etc/GMT0</option>
<option value="404">
404 - Etc/GMT-0</option>
<option value="405">
405 - Etc/GMT-1</option>
<option value="406">
406 - Etc/GMT-10</option>
<option value="407">
407 - Etc/GMT-11</option>
<option value="408">
408 - Etc/GMT-12</option>
<option value="409">
409 - Etc/GMT-13</option>
<option value="410">
410 - Etc/GMT-14</option>
<option value="411">
411 - Etc/GMT-2</option>
<option value="412">
412 - Etc/GMT-3</option>
<option value="413">
413 - Etc/GMT-4</option>
<option value="414">
414 - Etc/GMT-5</option>
<option value="415">
415 - Etc/GMT-6</option>
<option value="416">
416 - Etc/GMT-7</option>
<option value="417">
417 - Etc/GMT-8</option>
<option value="418">
418 - Etc/GMT-9</option>
<option value="419">
419 - Etc/Greenwich</option>
<option value="420">
420 - Etc/UCT</option>
<option value="421">
421 - Etc/Universal</option>
<option value="422">
422 - Etc/UTC</option>
<option value="423">
423 - Etc/Zulu</option>
<option value="424">
424 - Europe/Amsterdam</option>
<option value="425">
425 - Europe/Andorra</option>
<option value="426">
426 - Europe/Astrakhan</option>
<option value="427">
427 - Europe/Athens</option>
<option value="428">
428 - Europe/Belfast</option>
<option value="429">
429 - Europe/Belgrade</option>
<option value="430">
430 - Europe/Berlin</option>
<option value="431">
431 - Europe/Bratislava</option>
<option value="432">
432 - Europe/Brussels</option>
<option value="433">
433 - Europe/Bucharest</option>
<option value="434">
434 - Europe/Budapest</option>
<option value="435">
435 - Europe/Busingen</option>
<option value="436">
436 - Europe/Chisinau</option>
<option value="437">
437 - Europe/Copenhagen</option>
<option value="438">
438 - Europe/Dublin</option>
<option value="439">
439 - Europe/Gibraltar</option>
<option value="440">
440 - Europe/Guernsey</option>
<option value="441">
441 - Europe/Helsinki</option>
<option value="442">
442 - Europe/Isle_of_Man</option>
<option value="443">
443 - Europe/Istanbul</option>
<option value="444">
444 - Europe/Jersey</option>
<option value="445">
445 - Europe/Kaliningrad</option>
<option value="446">
446 - Europe/Kiev</option>
<option value="447">
447 - Europe/Kirov</option>
<option value="448">
448 - Europe/Lisbon</option>
<option value="449">
449 - Europe/Ljubljana</option>
<option value="450">
450 - Europe/London</option>
<option value="451">
451 - Europe/Luxembourg</option>
<option value="452">
452 - Europe/Madrid</option>
<option value="453">
453 - Europe/Malta</option>
<option value="454">
454 - Europe/Mariehamn</option>
<option value="455">
455 - Europe/Minsk</option>
<option value="456">
456 - Europe/Monaco</option>
<option value="457">
457 - Europe/Moscow</option>
<option value="458">
458 - Europe/Nicosia</option>
<option value="459">
459 - Europe/Oslo</option>
<option value="460">
460 - Europe/Paris</option>
<option value="461">
461 - Europe/Podgorica</option>
<option value="462">
462 - Europe/Prague</option>
<option value="463">
463 - Europe/Riga</option>
<option value="464">
464 - Europe/Rome</option>
<option value="465">
465 - Europe/Samara</option>
<option value="466">
466 - Europe/San_Marino</option>
<option value="467">
467 - Europe/Sarajevo</option>
<option value="468">
468 - Europe/Saratov</option>
<option value="469">
469 - Europe/Simferopol</option>
<option value="470">
470 - Europe/Skopje</option>
<option value="471">
471 - Europe/Sofia</option>
<option value="472">
472 - Europe/Stockholm</option>
<option value="473">
473 - Europe/Tallinn</option>
<option value="474">
474 - Europe/Tirane</option>
<option value="475">
475 - Europe/Tiraspol</option>
<option value="476">
476 - Europe/Ulyanovsk</option>
<option value="477">
477 - Europe/Uzhgorod</option>
<option value="478">
478 - Europe/Vaduz</option>
<option value="479">
479 - Europe/Vatican</option>
<option value="480">
480 - Europe/Vienna</option>
<option value="481">
481 - Europe/Vilnius</option>
<option value="482">
482 - Europe/Volgograd</option>
<option value="483">
483 - Europe/Warsaw</option>
<option value="484">
484 - Europe/Zagreb</option>
<option value="485">
485 - Europe/Zaporozhye</option>
<option value="486">
486 - Europe/Zurich</option>
<option value="487">
487 - GB</option>
<option value="488">
488 - GB-Eire</option>
<option value="489">
489 - GMT</option>
<option value="490">
490 - GMT+0</option>
<option value="491">
491 - GMT0</option>
<option value="492">
492 - GMT-0</option>
<option value="493">
493 - Greenwich</option>
<option value="494">
494 - Hongkong</option>
<option value="495">
495 - HST</option>
<option value="496">
496 - Iceland</option>
<option value="497">
497 - Indian/Antananarivo</option>
<option value="498">
498 - Indian/Chagos</option>
<option value="499">
499 - Indian/Christmas</option>
<option value="500">
500 - Indian/Cocos</option>
<option value="501">
501 - Indian/Comoro</option>
<option value="502">
502 - Indian/Kerguelen</option>
<option value="503">
503 - Indian/Mahe</option>
<option value="504">
504 - Indian/Maldives</option>
<option value="505">
505 - Indian/Mauritius</option>
<option value="506">
506 - Indian/Mayotte</option>
<option value="507">
507 - Indian/Reunion</option>
<option value="508">
508 - Iran</option>
<option value="509">
509 - Israel</option>
<option value="510">
510 - Jamaica</option>
<option value="511">
511 - Japan</option>
<option value="512">
512 - Kwajalein</option>
<option value="513">
513 - Libya</option>
<option value="514">
514 - MET</option>
<option value="515">
515 - Mexico/BajaNorte</option>
<option value="516">
516 - Mexico/BajaSur</option>
<option value="517">
517 - Mexico/General</option>
<option value="518">
518 - MST</option>
<option value="519">
519 - MST7MDT</option>
<option value="520">
520 - Navajo</option>
<option value="521">
521 - NZ</option>
<option value="522">
522 - NZ-CHAT</option>
<option value="523">
523 - Pacific/Apia</option>
<option value="524">
524 - Pacific/Auckland</option>
<option value="525">
525 - Pacific/Bougainville</option>
<option value="526">
526 - Pacific/Chatham</option>
<option value="527">
527 - Pacific/Chuuk</option>
<option value="528">
528 - Pacific/Easter</option>
<option value="529">
529 - Pacific/Efate</option>
<option value="530">
530 - Pacific/Enderbury</option>
<option value="531">
531 - Pacific/Fakaofo</option>
<option value="532">
532 - Pacific/Fiji</option>
<option value="533">
533 - Pacific/Funafuti</option>
<option value="534">
534 - Pacific/Galapagos</option>
<option value="535">
535 - Pacific/Gambier</option>
<option value="536">
536 - Pacific/Guadalcanal</option>
<option value="537">
537 - Pacific/Guam</option>
<option value="538">
538 - Pacific/Honolulu</option>
<option value="539">
539 - Pacific/Johnston</option>
<option value="540">
540 - Pacific/Kiritimati</option>
<option value="541">
541 - Pacific/Kosrae</option>
<option value="542">
542 - Pacific/Kwajalein</option>
<option value="543">
543 - Pacific/Majuro</option>
<option value="544">
544 - Pacific/Marquesas</option>
<option value="545">
545 - Pacific/Midway</option>
<option value="546">
546 - Pacific/Nauru</option>
<option value="547">
547 - Pacific/Niue</option>
<option value="548">
548 - Pacific/Norfolk</option>
<option value="549">
549 - Pacific/Noumea</option>
<option value="550">
550 - Pacific/Pago_Pago</option>
<option value="551">
551 - Pacific/Palau</option>
<option value="552">
552 - Pacific/Pitcairn</option>
<option value="553">
553 - Pacific/Pohnpei</option>
<option value="554">
554 - Pacific/Ponape</option>
<option value="555">
555 - Pacific/Port_Moresby</option>
<option value="556">
556 - Pacific/Rarotonga</option>
<option value="557">
557 - Pacific/Saipan</option>
<option value="558">
558 - Pacific/Samoa</option>
<option value="559">
559 - Pacific/Tahiti</option>
<option value="560">
560 - Pacific/Tarawa</option>
<option value="561">
561 - Pacific/Tongatapu</option>
<option value="562">
562 - Pacific/Truk</option>
<option value="563">
563 - Pacific/Wake</option>
<option value="564">
564 - Pacific/Wallis</option>
<option value="565">
565 - Pacific/Yap</option>
<option value="566">
566 - Poland</option>
<option value="567">
567 - Portugal</option>
<option value="568">
568 - PRC</option>
<option value="569">
569 - PST8PDT</option>
<option value="570">
570 - ROC</option>
<option value="571">
571 - ROK</option>
<option value="572">
572 - Singapore</option>
<option value="573">
573 - Turkey</option>
<option value="574">
574 - UCT</option>
<option value="575">
575 - Universal</option>
<option value="576">
576 - US/Alaska</option>
<option value="577">
577 - US/Aleutian</option>
<option value="578">
578 - US/Arizona</option>
<option value="579">
579 - US/Central</option>
<option value="580">
580 - US/Eastern</option>
<option value="581">
581 - US/East-Indiana</option>
<option value="582">
582 - US/Hawaii</option>
<option value="583">
583 - US/Indiana-Starke</option>
<option value="584">
584 - US/Michigan</option>
<option value="585">
585 - US/Mountain</option>
<option value="586">
586 - US/Pacific</option>
<option value="587">
587 - US/Pacific-New</option>
<option value="588">
588 - US/Samoa</option>
<option value="589">
589 - UTC</option>
<option value="590">
590 - WET</option>
<option value="591">
591 - W-SU</option>
<option value="592">
592 - Zulu</option>
</select>
</div>
</div>
<div class="grid-x grid-padding-x">
<div class="large-12 medium-12 small-12 text-center">
<button type="submit" name="Submit" class="button success"><i class="fa-duotone fa-magnifying-glass fa-fw"></i>Cerca</button>
</div>
</div>
</form>
</fieldset>
