<fieldset class="filtri fieldset hide hide-for-print" id="filtri" data-toggler=".hide">
<legend>Cerca</legend>
<form id="formRicerca" class="formRicerca" method="get" action="/admin/view.aspx">
<input type="hidden" name="CoreModules_Ky" value="33" />
<input type="hidden" name="CoreEntities_Ky" value="231" />
<input type="hidden" name="CoreGrids_Ky" value="244" />
<div class="grid-x grid-padding-x number">
<div class="large-2 medium-2 small-4 cell">
<label for="Officina_Ky" class="large-text-right small-text-left middle">Codice</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="Officina_Ky" id="Officina_Ky" class="input-group-field" placeholder="ricerca per Codice">
</div>
</div>
<div class="grid-x grid-padding-x data">
<div class="large-2 medium-2 small-4 cell">
<label for="Officina_DataConsegna" class="large-text-right small-text-left middle">Data Consegna</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="Officina_DataConsegna" id="Officina_DataConsegna" class="input-group-field" placeholder="ricerca per Data Consegna">
</div>
</div>
<div class="grid-x grid-padding-x text">
<div class="large-2 medium-2 small-4 cell">
<label for="Officina_Nominativo" class="large-text-right small-text-left middle">Nominativo</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="Officina_Nominativo" id="Officina_Nominativo" class="input-group-field" placeholder="ricerca per Nominativo">
</div>
</div>
<div class="grid-x grid-padding-x text">
<div class="large-2 medium-2 small-4 cell">
<label for="Officina_TargaVettura" class="large-text-right small-text-left middle">Targa Vettura</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="Officina_TargaVettura" id="Officina_TargaVettura" class="input-group-field" placeholder="ricerca per Targa Vettura">
</div>
</div>
<div class="grid-x grid-padding-x text">
<div class="large-2 medium-2 small-4 cell">
<label for="Officina_Venditore" class="large-text-right small-text-left middle">Venditore</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="Officina_Venditore" id="Officina_Venditore" class="input-group-field" placeholder="ricerca per Venditore">
</div>
</div>
<div class="grid-x grid-padding-x">
<div class="large-12 medium-12 small-12 text-center">
<button type="submit" name="Submit" class="button success"><i class="fa-duotone fa-magnifying-glass fa-fw"></i>Cerca</button>
</div>
</div>
</form>
</fieldset>
