<fieldset class="filtri fieldset hide hide-for-print" id="filtri" data-toggler=".hide">
	<legend>Cerca tags</legend>
	<form id="formRicerca" class="formRicerca" method="get" action="/admin/view.aspx?CoreModules_Ky=9&CoreEntities_Ky=102&CoreGrids_Ky=85">
    <div class="grid-x grid-padding-x">
	    <div class="large-2 medium-2 small-3 cell">
	      <label for="CMSLink_Titolo" class="large-text-right small-text-left middle">Ricerca per titolo</label>
	    </div>
    	<div class="large-8 medium-8 small-6 cell">
				<input type="text" name="CMSLink_Titolo" id="CMSLink_Titolo" placeholder="ricerca per titolo" />
			</div>
	    <div class="cell shrink">
      	<button type="submit" value="cerca" name="cerca" class="button postfix secondary"><i class="fa-duotone fa-magnifying-glass fa-fw"></i></button>
      </div>
    </div>
  </form>
</fieldset>
