<!--<div class="banner2"> -->
<!--<script type="text/javascript"> -->
<!-- google_ad_client = "ca-pub-0225194185843800";
    /* outletmobilidesign 300x250 */
    google_ad_slot = "2424792506";
    google_ad_width = 300;
    google_ad_height = 250;
    //-->
<!-- </script> -->
<!-- <script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script> -->
   
<!-- </div> -->
  

<div class="colonnadx-social">
			<div>
    			<ul class="colonnadx">
     			 <li class="colonnadx"><img src="/images/ico-facebook.jpg" width="20" height="18" hspace="5" align="left" /><a href="http://www.facebook.com">Seguici su facebook</a></li>
                 <li class="colonnadx"><img src="/images/ico-amico.png" width="20" height="18" hspace="5" align="left" /><a href="#">Segnala ad un amico</a></li>
    			</ul>
  			</div>
</div>
  
