<fieldset class="filtri fieldset hide hide-for-print" id="filtri" data-toggler=".hide">
<legend>Cerca</legend>
<form id="formRicerca" class="formRicerca" method="get" action="/admin/view.aspx">
<input type="hidden" name="CoreModules_Ky" value="1" />
<input type="hidden" name="CoreEntities_Ky" value="162" />
<input type="hidden" name="CoreGrids_Ky" value="36" />
<div class="grid-x grid-padding-x number">
<div class="large-2 medium-2 small-4 cell">
<label for="Anagrafiche_Ky" class="large-text-right small-text-left middle">id</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="Anagrafiche_Ky" id="Anagrafiche_Ky" class="input-group-field" placeholder="ricerca per id">
</div>
</div>
<div class="grid-x grid-padding-x text">
<div class="large-2 medium-2 small-4 cell">
<label for="Anagrafiche_RagioneSociale" class="large-text-right small-text-left middle">RagioneSociale</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="Anagrafiche_RagioneSociale" id="Anagrafiche_RagioneSociale" class="input-group-field" placeholder="ricerca per RagioneSociale">
</div>
</div>
<div class="grid-x grid-padding-x text">
<div class="large-2 medium-2 small-4 cell">
<label for="Anagrafiche_Codice" class="large-text-right small-text-left middle">Codice</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="Anagrafiche_Codice" id="Anagrafiche_Codice" class="input-group-field" placeholder="ricerca per Codice">
</div>
</div>
<div class="grid-x grid-padding-x text">
<div class="large-2 medium-2 small-4 cell">
<label for="Anagrafiche_ParoleChiave" class="large-text-right small-text-left middle">Parole Chiave</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="Anagrafiche_ParoleChiave" id="Anagrafiche_ParoleChiave" class="input-group-field" placeholder="ricerca per Parole Chiave">
</div>
</div>
<div class="grid-x grid-padding-x text">
<div class="large-2 medium-2 small-4 cell">
<label for="Anagrafiche_PartitaIVA" class="large-text-right small-text-left middle">Partita IVA</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="Anagrafiche_PartitaIVA" id="Anagrafiche_PartitaIVA" class="input-group-field" placeholder="ricerca per Partita IVA">
</div>
</div>
<div class="grid-x grid-padding-x text">
<div class="large-2 medium-2 small-4 cell">
<label for="Anagrafiche_Telefono" class="large-text-right small-text-left middle">Telefono</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="Anagrafiche_Telefono" id="Anagrafiche_Telefono" class="input-group-field" placeholder="ricerca per Telefono">
</div>
</div>
<div class="grid-x grid-padding-x text">
<div class="large-2 medium-2 small-4 cell">
<label for="Anagrafiche_EmailAmministrazione" class="large-text-right small-text-left middle">Email amministrazione</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="Anagrafiche_EmailAmministrazione" id="Anagrafiche_EmailAmministrazione" class="input-group-field" placeholder="ricerca per Email amministrazione">
</div>
</div>
<div class="grid-x grid-padding-x text">
<div class="large-2 medium-2 small-4 cell">
<label for="Anagrafiche_EmailContatti" class="large-text-right small-text-left middle">Email contatti</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<input type="text" name="Anagrafiche_EmailContatti" id="Anagrafiche_EmailContatti" class="input-group-field" placeholder="ricerca per Email contatti">
</div>
</div>
<div class="grid-x grid-padding-x join">
<div class="large-2 medium-2 small-4 cell">
<label for="AnagraficheTipo_Ky" class="large-text-right small-text-left middle">Tipo</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<select name="AnagraficheTipo_Ky" id="Anagrafiche_Ky" placeholder="Tipo">
<option></option>
<option value="1">
Cliente</option>
<option value="5">
Concorrenti</option>
<option value="4">
Fornitore</option>
<option value="3">
Lead</option>
<option value="6">
Rivenditori</option>
</select>
</div>
</div>
<div class="grid-x grid-padding-x join">
<div class="large-2 medium-2 small-4 cell">
<label for="AnagraficheCategorie_Ky" class="large-text-right small-text-left middle">Categoria</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<select name="AnagraficheCategorie_Ky" id="Anagrafiche_Ky" placeholder="Categoria">
<option></option>
<option value="1">
1 - Agenzia immobiliare</option>
<option value="2">
2 - Demolitore auto</option>
<option value="3">
3 - Industria</option>
<option value="4">
4 - Arredamento</option>
<option value="5">
5 - Impresa Edile, Edilizia</option>
<option value="6">
6 - Medici, Farmacie, Dentisti</option>
<option value="7">
7 - Agricoltura</option>
<option value="8">
8 - Turismo: Hotel, alberghi</option>
<option value="9">
9 - Web Agency</option>
<option value="10">
10 - Finanza: Banche, assicurazioni</option>
<option value="11">
11 - Trasporti</option>
<option value="12">
12 - Concessionarie</option>
<option value="13">
13 - Nautica</option>
<option value="14">
14 - Ristoranti, Pizzerie, pub, bar</option>
<option value="15">
15 - Carrozzeria</option>
<option value="16">
16 - Alimentare</option>
<option value="17">
17 - Associazione, no profit</option>
<option value="18">
18 - Abbigliamento</option>
<option value="19">
19 - Agenzia Comunicazione</option>
<option value="20">
20 - Ecommerce</option>
<option value="21">
21 - Sport</option>
<option value="22">
22 - Commercialisti</option>
<option value="23">
23 - Impresa di servizi: pulizie, trasporti, ecc</option>
<option value="24">
24 - Giornale, magazine, giornalista</option>
<option value="25">
25 - Fotografi</option>
<option value="26">
26 - Officina</option>
<option value="27">
27 - Istruzione: scuole, istituti, ecc</option>
<option value="28">
28 - Avvocati</option>
<option value="29">
29 - Assicurazioni</option>
<option value="30">
30 - Amministratore di condominio</option>
<option value="31">
31 - Consulenze</option>
<option value="32">
32 - Commercio</option>
<option value="33">
33 - Informatica</option>
<option value="34">
34 - Spettacolo: cantante, teatro, danza</option>
<option value="35">
35 - Arte</option>
<option value="36">
36 - Pubblica amministrazione, province, comuni</option>
<option value="37">
37 - Sanità</option>
<option value="38">
38 - Media, televesioni</option>
<option value="39">
39 - Energia</option>
<option value="40">
40 - Negozio al dettaglio: articoli per la casa, ecc</option>
<option value="41">
41 - Lead</option>
<option value="42">
42 - Enoteca, vendita vino</option>
<option value="43">
43 - Immobiliare</option>
<option value="45">
45 - Pubblicità</option>
<option value="46">
46 - Automotive</option>
<option value="47">
47 - Portale</option>
</select>
</div>
</div>
<div class="grid-x grid-padding-x join">
<div class="large-2 medium-2 small-4 cell">
<label for="AnagraficheTipologia_Ky" class="large-text-right small-text-left middle">TipologiaCodice</label>
</div>
<div class="large-10 medium-10 small-8 cell">
<select name="AnagraficheTipologia_Ky" id="Anagrafiche_Ky" placeholder="TipologiaCodice">
<option></option>
<option value="7">
Altro</option>
<option value="2">
Azienda</option>
<option value="4">
Ditta individuale</option>
<option value="6">
Ente no profit</option>
<option value="3">
Libero professionista</option>
<option value="1">
Privato</option>
<option value="5">
Pubblica amministrazione</option>
</select>
</div>
</div>
<div class="grid-x grid-padding-x">
<div class="large-12 medium-12 small-12 text-center">
<button type="submit" name="Submit" class="button success"><i class="fa-duotone fa-magnifying-glass fa-fw"></i>Cerca</button>
</div>
</div>
</form>
</fieldset>
