<% if (strAzione!="new"){ %>
<div class="grid-x grid-padding-x">
  <div class="small-12 medium-12 large-12 cell">
		<a name="log"></a>
		<div class="card">
		  <div class="card-divider">
					<h2><i class="fa-duotone fa-chart-mixed fa-lg fa-fw"></i>Grafici</h2>
			</div>        
	  	<div class="card-section">
			    <div id="PageSpeed-Score" class="grafico1"></div> 
			</div>
		</div>        
  </div>
</div>
<% } %>
